export const {
  AUTH_MICROSERVICE_URL,
  CATEGORY_MICROSERVICE_URL,
  PRODUCT_MICROSERVICE_URL,
  ORDER_MICROSERVICE_URL,
  PROPERTY_CATEGORY_MICROSERVICE_URL,
  PRODUCT_PROPERTY_MICROSERVICE_URL,
  PROPERTY_MICROSERVICE_URL,
} = process.env;
